version: "3.9"

services:

  # ======================
  # PostgreSQL
  # ======================
  datalog_postgres:
    image: postgres:15
    container_name: datalog_postgres
    environment:
      POSTGRES_DB: datalog
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 0655084017a371192df3
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  # ======================
  # API (Flask DEV)
  # ======================
  api:
    build:
      context: ./api
      dockerfile: Dockerfile.dev
    container_name: datalog_api
    working_dir: /app
    volumes:
      - ./api:/app
    env_file:
      - ./api/.env
    command: flask run --host=0.0.0.0 --port=5000 --debug
    depends_on:
      - datalog_postgres
    ports:
      - "5000:5000"


  # ======================
  # Front (Flask DEV)
  # ======================
  front:
    build:
      context: ./front
      dockerfile: Dockerfile.dev
    volumes:
      - ./front:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    depends_on:
      - api
      
volumes:
  pgdata:
